#!/usr/bin/env python3
"""Generate the routing truth table the Playwright harness serves.

The e2e suite must never guess when a question becomes an ML skill vs. text-to-SQL.
Instead of hard-coding that in JavaScript, we call the *real* backend rule
(:func:`src.agent.langgraph_agent.nodes.router.explain_routing`) over a fixed set
of questions and write the answers to ``harness/routing.generated.js``. The fake
backend then shapes each streamed answer from this file, so the UI shows exactly
what production routing would decide — the tests can drift only if the real rule
does.

Run directly (``python tests/e2e/generate_fixtures.py``) or via the Playwright
global setup, which runs it before the suite.
"""

from __future__ import annotations

import json
import os
import sys
from pathlib import Path

# Import the real routing rule from the repo.
ROOT = Path(__file__).resolve().parents[2]
sys.path.insert(0, str(ROOT))

# src.config.Settings needs a few env vars just to import; values are irrelevant.
os.environ.setdefault("AZURE_OPENAI_API_KEY", "test")
os.environ.setdefault("AZURE_OPENAI_ENDPOINT", "https://test.invalid")
os.environ.setdefault("METADATA_DB_HOST", "test")
os.environ.setdefault("METADATA_DB_NAME", "test")
os.environ.setdefault("METADATA_DB_USER", "test")
os.environ.setdefault("METADATA_DB_PASSWORD", "test")
os.environ.setdefault("INTERNAL_API_SECRET", "e2e-fixture-secret-0123456789abcdef")

from src.agent.langgraph_agent.nodes.router import explain_routing  # noqa: E402

# The canonical questions the harness and specs share. Keep these identical to
# the QUESTIONS map in harness/fixtures.js.
QUESTIONS = [
    "Show me total sales by region last month",
    "How many orders shipped yesterday?",
    "Total sales for the Bikes category by year",
    "Forecast profit for the next 8 weeks",
    "Is anything unusual in weekly profit?",
    "Forecast weekly revenue for a brand-new product line",
    "Show the correlation between marketing spend and revenue",
    "which ML models can I use?",
    "hello",
]


def build(ml_enabled: bool = True) -> dict:
    out = {}
    for q in QUESTIONS:
        pred = explain_routing(q, ml_skills_enabled=ml_enabled, analysis_override=None)
        out[q] = {
            "would_route": pred["would_route"],
            "source": pred["source"],
            "skill_hint": pred.get("skill_hint"),
            "reason": pred["reason"],
        }
    # One case with the per-request override, to prove "Answer with SQL instead".
    forced = explain_routing(
        "Forecast profit for the next 8 weeks", ml_skills_enabled=True, analysis_override=False,
    )
    out["__forecast_sql_override__"] = {
        "would_route": forced["would_route"], "source": forced["source"],
        "skill_hint": forced.get("skill_hint"), "reason": forced["reason"],
    }
    return out


def main() -> None:
    table = build(ml_enabled=True)
    disabled = build(ml_enabled=False)
    payload = {"enabled": table, "disabled": disabled}
    out_dir = Path(__file__).resolve().parent / "harness"
    out_dir.mkdir(parents=True, exist_ok=True)
    target = out_dir / "routing.generated.js"
    body = json.dumps(payload, indent=2, ensure_ascii=False)
    target.write_text(
        "// AUTOGENERATED by tests/e2e/generate_fixtures.py — do not edit.\n"
        "// Real routing predictions from src.agent.langgraph_agent.nodes.router.explain_routing.\n"
        f"window.__ROUTING_TRUTH__ = {body};\n",
        encoding="utf-8",
    )
    print(f"wrote {target} ({len(table)} questions)")


if __name__ == "__main__":
    main()
